### ISSUE TITLE
Block instruction emulation errors

### ISSUE THREAD

**Issue by EtchedPixels** [TimothyPMann/xtrs#2]
Block instructions do not allow interrupts to occur mid instruction
Block instructions incorrectly emulate a transfer over the currently executing instruction (eg for copy protection)

The following for example produces incorrect results

  start:  ld hl, overwritedata
            ld de, start
            ld bc, 64
            ldir

On a real Z80 it executes by doing an ldi and backing up the program counter for each byte. Interrupts may be taken at any point and also as in this case if the ldir is overwritten the CPU begins executing the new instruction not continuing the copy.

I can see why the implementation was done that way in the days of 386 boxes, but with multi-GHZ processors I'd say it's a nowdays a bug.

**Comment by TimothyPMann** [comment]
Fixed by merging pull request #21.
