### ISSUE TITLE
Model 4 Printer Port

### ISSUE THREAD

**Issue by EtchedPixels** [TimothyPMann/xtrs#23]
The documentation says that bits 0-3 of the status port are reserved.

However the Anitek Hyperdrive does the following

IN A,(F8H)
AND 0C
BIT 2,A
JR Z,L1
SET 7,A
OUT (84H),A

when doing some banking operations on the card.

Should these bits reflect 0x84 or is there some extra magic going on in the Hypermem card ?

**Comment by TimothyPMann** [comment]
That's a new one on me. I have a physical Model 4P and can try IN A,(F8H) on that to see what I get. And/or maybe I have a schematic that would show what input from F8 does.

**Comment by TimothyPMann** [comment]
The Model 4 technical reference manual that I found online has a schematic that claims the low 4 bits of input port F8 are connected to spare pins on the parallel port connector.

It's a bit tricky to decipher what pins they really are. The schematic uses pin numbering that doesn't match the Centronics connector pinouts I can find online. It looks like the schematic uses odd numbers for the pins on one side of the connector and even numbers on the other side, while the standard uses numbers 1-18 on one side and 19-36 on the other side, with pins 1 and 36 the same between the two numberings.

`
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  Centronics
 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35  Schematic

19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36  Centronics
 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36  Schematic
`

Working through that theory with (for instance) http://www.interfacebus.com/Design_Centronics_Connector_PinOuts.html, everything pretty much matches up. This makes the 8 bits from reading port F8 the following:

`
Bit   Schematic    Schematic   Centronics   Centronics
      pin number   pin name    pin number   pin name
---   ----------   --------    ----------   ----------
7     21           BUSY        11           BUSY
6     23           OUTPAPER    12           PAPER ERROR
5     25           UNIT SEL    13           SELECT OUT
4     28           FAULT       32           /FAULT
3     19           SPARE       10           /ACK
2     29           SPARE       15           SELECT IN
1     30           SPARE       33           Signal Ground
0     32           SPARE       34           Not used
`

**Comment by EtchedPixels** [comment]
Interesting - so presumably the hypermem borrowed those spare pins.

**Comment by TimothyPMann** [comment]
The Model 4P gate array schematic shows the same thing. I haven't pulled out the machine and turned it on yet.

I don't have a Radio Shack printer cable (34-pin card edge to 36-pin Centronics connector), so can't experiment easily with putting sending different inputs into the extra pins. I suppose I could use a 34-pin floppy cable just to bring the lines out to where they're easier to get at.

Hmm, I wonder which of the 36 Centronics pins is a no-connect to the 34-pin card edge, and if RS did some jumpering so that the omitted pins are unimportant ones. I'm sure that's documented somewhere...

**Comment by TimothyPMann** [comment]
My Model 4P doesn't power on -- the illuminated power switch lights up, but there is no other sign of life. It's been a few years since I tried to turn it on. Anyway it seems like the schematics are probably correct.
