### ISSUE TITLE
License clarification?

### ISSUE THREAD

**Issue by ulm** [TimothyPMann/xtrs#29]
I guess it is supposed to be a free software / open source license, but some people are picky about what rights are exactly granted. So I wonder if you could insert the word "redistributed" somewhere, so that it would say:

`This software may be copied, modified, redistributed, and used for any purpose without fee, ...`

**Comment by TimothyPMann** [comment]
What is different between "copied" and "redistributed"? Do people believe that "copied" means they can make a copy but can't give a copy to anyone else? Ugh.

**Comment by ulm** [comment]
Yes, I believe some people do. The language of popular free licenses tends to explicitly mention "distribute" or "redistribute".

For example, the ISC license says: "Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted ..."

Or the BSD license: "Redistribution and use in source and binary forms, with or without
modification, are permitted ..."

**Comment by TimothyPMann** [comment]
It would be nice to change the license to a standard one like 2-clause BSD or MIT. I suppose I don't really care about people marking modified versions with their name and date. I doubt anyone remembers to do that anyway.

The original xtrs-1.0 stuff is under a license that is basically the same as 2-clause BSD or MIT.

**Comment by TimothyPMann** [comment]
Ulrich, may I change the licens on settime.z80 to the MIT license? That's what I'm changing my own contributions to. See https://opensource.org/licenses/MIT.

**Comment by ulm** [comment]
> Ulrich, may I change the license on settime.z80 to the MIT license? That's what I'm changing my own contributions to. See https://opensource.org/licenses/MIT.

Sure, MIT works for me.

**Comment by TimothyPMann** [comment]
I changed all I could. I don't have current contact info for Pete Cervasio. I found a twitter account for someone with the same name, but he didn't respond to my tweet.
