### ISSUE TITLE
RETI emulation is incorrect

### ISSUE THREAD

**Issue by EtchedPixels** [TimothyPMann/xtrs#3]
Going through the old fixes I did to sdltrs

Your emulator mishandles RETI. RETI like RETN copies IFF2 back to IFF1.

**Comment by EtchedPixels** [comment]
Patch

[a1.txt](https://github.com/TimothyPMann/xtrs/files/2010919/a1.txt)

**Comment by TimothyPMann** [comment]
Merged -- thanks.
