### ISSUE TITLE
Wrong track info in NEWDOS/80 with a mkdisk created SSSD disk image

### ISSUE THREAD

**Issue by jwich71** [TimothyPMann/xtrs#34]
I am using xtrs 4.9d on F33 Linux with a TRS-80 Model 1 ROM file and NEWDOS/80 v2.

I just created a blank disk image with mkdisk -k -s1 -d1 blank.dmk (5.25" SSSD DMK format) and used that as disk1-1 in xtrs.
I would expect NEWDOS to show me the disk with 35 or 40 tracks, but the DIR,1 command shows the disk with 80 tracks.
Also the FREE command shows the disk info with 80 tracks. Also all other disk images are always shown with 80 TRKS.
I started xtrs with the options -scale 2 -autodelay -doubler none -nodoublestep [-truedam]. 
This behaviour makes me a bit curious, because on my real TRS-80, the disk info shows the correct 35 TRKS (an SSSD disk created from a disk image).

For help I would be very grateful.

**Comment by TimothyPMann** [comment]
A blank disk image is unformatted, similar to a bulk-erased physical disk, so NEWDOS can't know how many tracks it has. In fact, when I try the same thing you say you did, NEWDOS/80 gives me "DIRECTORY READ ERROR" on drive 1 for both DIR,1 and FREE commands. That's what I'd expect with an unformatted disk. So I am not really sure what you did to get it to show 80 tracks.

I guess you may have done FORMAT :1 in NEWDOS before DIR or FREE, but you forgot to mention that in your report. Apparently NEWDOS/80 tries to format 80 tracks by default. xtrs emulates a drive that can format as many tracks as you want, up to 255 or so. It doesn't have a way to limit the emulated drive to 35 or 40 tracks.

I am not a NEWDOS expert, but it looks like you can tell NEWDOS to format only 35 or 40 tracks using PDRIVE's TC option. See http://www.trs-80.com/wordpress/dos-newdos80/.
