### ISSUE TITLE
Interrupt handling mishandles IFF2

### ISSUE THREAD

**Issue by EtchedPixels** [TimothyPMann/xtrs#4]
You can see this if you do a ld a,i in an interrupt and check the flags. On a real system IFF1 and IFF2 are cleared, on your emulation only IFF1 is. This causes code that uses ld a,i push af ... pop af, jpcc sequences to save/restore IRQ state to fail on xtrs.

**Comment by EtchedPixels** [comment]
Patch

[a3.txt](https://github.com/TimothyPMann/xtrs/files/2010917/a3.txt)

**Comment by TimothyPMann** [comment]
Thanks!
